use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq)]
pub enum OptionType {
    Bool,
    Int,
    Float,
    Color,
    Gradient,
    String,
    Vec2,
    Enum,
}

#[derive(Debug, Clone)]
pub struct OptionDef {
    pub name: String,
    pub option_type: OptionType,
    pub default: String,
    pub description: String,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub step: Option<f64>,
    pub choices: Option<Vec<String>>,
}

#[derive(Debug, Clone)]
pub struct Section {
    pub name: String,
    pub title: String,
    pub options: Vec<OptionDef>,
}

#[derive(Debug, Clone)]
pub struct Tab {
    pub id: String,
    pub title: String,
    pub icon: char,
    pub sections: Vec<Section>,
}

pub fn get_schema() -> Vec<Tab> {
    vec![
        Tab {
            id: "general".to_string(),
            title: "General".to_string(),
            icon: '⚙',
            sections: vec![
                Section {
                    name: "general".to_string(),
                    title: "General Settings".to_string(),
                    options: vec![
                        OptionDef {
                            name: "border_size".to_string(),
                            option_type: OptionType::Int,
                            default: "1".to_string(),
                            description: "Border size in pixels".to_string(),
                            min: Some(0.0),
                            max: Some(10.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "gaps_in".to_string(),
                            option_type: OptionType::Int,
                            default: "5".to_string(),
                            description: "Gaps between windows".to_string(),
                            min: Some(0.0),
                            max: Some(50.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "gaps_out".to_string(),
                            option_type: OptionType::Int,
                            default: "20".to_string(),
                            description: "Gaps between windows and edges".to_string(),
                            min: Some(0.0),
                            max: Some(100.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "gaps_workspaces".to_string(),
                            option_type: OptionType::Int,
                            default: "0".to_string(),
                            description: "Gaps between workspaces".to_string(),
                            min: Some(0.0),
                            max: Some(50.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "col.active_border".to_string(),
                            option_type: OptionType::Gradient,
                            default: "0xffffffff".to_string(),
                            description: "Active window border color".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "col.inactive_border".to_string(),
                            option_type: OptionType::Gradient,
                            default: "0xff444444".to_string(),
                            description: "Inactive window border color".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "layout".to_string(),
                            option_type: OptionType::Enum,
                            default: "dwindle".to_string(),
                            description: "Window layout".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: Some(vec!["dwindle".to_string(), "master".to_string()]),
                        },
                        OptionDef {
                            name: "resize_on_border".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Resize by clicking borders".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "extend_border_grab_area".to_string(),
                            option_type: OptionType::Int,
                            default: "15".to_string(),
                            description: "Border grab area".to_string(),
                            min: Some(0.0),
                            max: Some(50.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "hover_icon_on_border".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Show cursor on border hover".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "no_focus_fallback".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "No focus fallback".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "allow_tearing".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Allow tearing".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "general:snap".to_string(),
                    title: "Window Snapping".to_string(),
                    options: vec![
                        OptionDef {
                            name: "enabled".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Enable floating window snapping".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "window_gap".to_string(),
                            option_type: OptionType::Int,
                            default: "10".to_string(),
                            description: "Gap before snapping".to_string(),
                            min: Some(0.0),
                            max: Some(50.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "monitor_gap".to_string(),
                            option_type: OptionType::Int,
                            default: "10".to_string(),
                            description: "Monitor edge snap gap".to_string(),
                            min: Some(0.0),
                            max: Some(50.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "border_overlap".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Snap with border overlap".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "dwindle".to_string(),
                    title: "Dwindle Layout".to_string(),
                    options: vec![
                        OptionDef {
                            name: "pseudotile".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Enable pseudotiling".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "force_split".to_string(),
                            option_type: OptionType::Int,
                            default: "0".to_string(),
                            description: "Force split (0=mouse, 1=left, 2=right)".to_string(),
                            min: Some(0.0),
                            max: Some(2.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "preserve_split".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Preserve split direction".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "smart_split".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Cursor-based split direction".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "smart_resizing".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Mouse-based resize direction".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "permanent_direction_override".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Persist preselect direction".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "special_scale_factor".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Special workspace scale".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "split_width_multiplier".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Auto-split width multiplier".to_string(),
                            min: Some(0.5),
                            max: Some(2.0),
                            step: Some(0.1),
                            choices: None,
                        },
                        OptionDef {
                            name: "use_active_for_splits".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Prefer active window for splits".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "default_split_ratio".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Default split ratio".to_string(),
                            min: Some(0.1),
                            max: Some(1.9),
                            step: Some(0.1),
                            choices: None,
                        },
                        OptionDef {
                            name: "split_bias".to_string(),
                            option_type: OptionType::Int,
                            default: "0".to_string(),
                            description: "Split ratio receiver (0=directional, 1=current)"
                                .to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "precise_mouse_move".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Mouse-precise window drop".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "master".to_string(),
                    title: "Master Layout".to_string(),
                    options: vec![
                        OptionDef {
                            name: "allow_small_split".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Horizontal split for masters".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "special_scale_factor".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Special workspace scale".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "mfact".to_string(),
                            option_type: OptionType::Float,
                            default: "0.55".to_string(),
                            description: "Master area ratio".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "new_status".to_string(),
                            option_type: OptionType::Enum,
                            default: "slave".to_string(),
                            description: "New window position".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: Some(vec![
                                "master".to_string(),
                                "slave".to_string(),
                                "inherit".to_string(),
                            ]),
                        },
                        OptionDef {
                            name: "new_on_top".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "New windows on top".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "new_on_active".to_string(),
                            option_type: OptionType::Enum,
                            default: "none".to_string(),
                            description: "New window relative position".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: Some(vec![
                                "before".to_string(),
                                "after".to_string(),
                                "none".to_string(),
                            ]),
                        },
                        OptionDef {
                            name: "orientation".to_string(),
                            option_type: OptionType::Enum,
                            default: "left".to_string(),
                            description: "Master orientation".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: Some(vec![
                                "left".to_string(),
                                "right".to_string(),
                                "top".to_string(),
                                "bottom".to_string(),
                                "center".to_string(),
                            ]),
                        },
                        OptionDef {
                            name: "inherit_fullscreen".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Inherit fullscreen on swap".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "slave_count_for_center_master".to_string(),
                            option_type: OptionType::Int,
                            default: "2".to_string(),
                            description: "Min slaves for center mode".to_string(),
                            min: Some(0.0),
                            max: Some(10.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "center_master_fallback".to_string(),
                            option_type: OptionType::Enum,
                            default: "left".to_string(),
                            description: "Fallback when few slaves".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: Some(vec![
                                "left".to_string(),
                                "right".to_string(),
                                "top".to_string(),
                                "bottom".to_string(),
                            ]),
                        },
                        OptionDef {
                            name: "smart_resizing".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Mouse-based resize direction".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "drop_at_cursor".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Drop windows at cursor".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "always_keep_position".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Keep master position when alone".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
            ],
        },
        Tab {
            id: "decoration".to_string(),
            title: "Decoration".to_string(),
            icon: '🎨',
            sections: vec![
                Section {
                    name: "decoration".to_string(),
                    title: "Decoration".to_string(),
                    options: vec![
                        OptionDef {
                            name: "rounding".to_string(),
                            option_type: OptionType::Int,
                            default: "0".to_string(),
                            description: "Corner radius".to_string(),
                            min: Some(0.0),
                            max: Some(30.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "rounding_power".to_string(),
                            option_type: OptionType::Float,
                            default: "2.0".to_string(),
                            description: "Rounding curve".to_string(),
                            min: Some(1.0),
                            max: Some(10.0),
                            step: Some(0.1),
                            choices: None,
                        },
                        OptionDef {
                            name: "active_opacity".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Active window opacity".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "inactive_opacity".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Inactive window opacity".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "fullscreen_opacity".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Fullscreen opacity".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "dim_inactive".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Dim inactive windows".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "dim_strength".to_string(),
                            option_type: OptionType::Float,
                            default: "0.5".to_string(),
                            description: "Dim strength".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "dim_special".to_string(),
                            option_type: OptionType::Float,
                            default: "0.2".to_string(),
                            description: "Special workspace dim".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "dim_around".to_string(),
                            option_type: OptionType::Float,
                            default: "0.4".to_string(),
                            description: "Dim around strength".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "decoration:blur".to_string(),
                    title: "Blur".to_string(),
                    options: vec![
                        OptionDef {
                            name: "enabled".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Enable blur".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "size".to_string(),
                            option_type: OptionType::Int,
                            default: "8".to_string(),
                            description: "Blur size".to_string(),
                            min: Some(1.0),
                            max: Some(20.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "passes".to_string(),
                            option_type: OptionType::Int,
                            default: "1".to_string(),
                            description: "Blur passes".to_string(),
                            min: Some(1.0),
                            max: Some(10.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "ignore_opacity".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Ignore window opacity".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "new_optimizations".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "New optimizations".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "xray".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "X-ray mode".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "noise".to_string(),
                            option_type: OptionType::Float,
                            default: "0.0117".to_string(),
                            description: "Noise amount".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.01),
                            choices: None,
                        },
                        OptionDef {
                            name: "contrast".to_string(),
                            option_type: OptionType::Float,
                            default: "0.8916".to_string(),
                            description: "Contrast".to_string(),
                            min: Some(0.0),
                            max: Some(2.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "brightness".to_string(),
                            option_type: OptionType::Float,
                            default: "0.8172".to_string(),
                            description: "Brightness".to_string(),
                            min: Some(0.0),
                            max: Some(2.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "vibrancy".to_string(),
                            option_type: OptionType::Float,
                            default: "0.1696".to_string(),
                            description: "Vibrancy".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.05),
                            choices: None,
                        },
                        OptionDef {
                            name: "special".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Blur special workspace".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "popups".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Blur popups".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "decoration:shadow".to_string(),
                    title: "Shadow".to_string(),
                    options: vec![
                        OptionDef {
                            name: "enabled".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Enable shadows".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "range".to_string(),
                            option_type: OptionType::Int,
                            default: "4".to_string(),
                            description: "Shadow range".to_string(),
                            min: Some(0.0),
                            max: Some(50.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "render_power".to_string(),
                            option_type: OptionType::Int,
                            default: "3".to_string(),
                            description: "Falloff power".to_string(),
                            min: Some(1.0),
                            max: Some(4.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "sharp".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Sharp shadows".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "ignore_window".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Ignore window".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "color".to_string(),
                            option_type: OptionType::Color,
                            default: "0xee1a1a1a".to_string(),
                            description: "Shadow color".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "offset".to_string(),
                            option_type: OptionType::Vec2,
                            default: "0 0".to_string(),
                            description: "Shadow offset".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "scale".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Shadow scale".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.1),
                            choices: None,
                        },
                    ],
                },
            ],
        },
        Tab {
            id: "input".to_string(),
            title: "Input".to_string(),
            icon: '⌨',
            sections: vec![
                Section {
                    name: "input".to_string(),
                    title: "Keyboard & Mouse".to_string(),
                    options: vec![
                        OptionDef {
                            name: "kb_layout".to_string(),
                            option_type: OptionType::String,
                            default: "us".to_string(),
                            description: "Keyboard layout".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "kb_variant".to_string(),
                            option_type: OptionType::String,
                            default: "".to_string(),
                            description: "Keyboard variant".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "kb_options".to_string(),
                            option_type: OptionType::String,
                            default: "".to_string(),
                            description: "XKB options".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "numlock_by_default".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Numlock on startup".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "repeat_rate".to_string(),
                            option_type: OptionType::Int,
                            default: "25".to_string(),
                            description: "Key repeat rate".to_string(),
                            min: Some(1.0),
                            max: Some(100.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "repeat_delay".to_string(),
                            option_type: OptionType::Int,
                            default: "600".to_string(),
                            description: "Key repeat delay (ms)".to_string(),
                            min: Some(100.0),
                            max: Some(2000.0),
                            step: Some(50.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "sensitivity".to_string(),
                            option_type: OptionType::Float,
                            default: "0.0".to_string(),
                            description: "Mouse sensitivity".to_string(),
                            min: Some(-1.0),
                            max: Some(1.0),
                            step: Some(0.1),
                            choices: None,
                        },
                        OptionDef {
                            name: "accel_profile".to_string(),
                            option_type: OptionType::Enum,
                            default: "".to_string(),
                            description: "Acceleration".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: Some(vec![
                                "".to_string(),
                                "adaptive".to_string(),
                                "flat".to_string(),
                            ]),
                        },
                        OptionDef {
                            name: "force_no_accel".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Force no acceleration".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "left_handed".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Left handed mode".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "natural_scroll".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Natural scrolling".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "scroll_factor".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Scroll multiplier".to_string(),
                            min: Some(0.1),
                            max: Some(5.0),
                            step: Some(0.1),
                            choices: None,
                        },
                        OptionDef {
                            name: "follow_mouse".to_string(),
                            option_type: OptionType::Int,
                            default: "1".to_string(),
                            description: "Focus follows mouse (0-3)".to_string(),
                            min: Some(0.0),
                            max: Some(3.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "mouse_refocus".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Refocus on mouse move".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "float_switch_override_focus".to_string(),
                            option_type: OptionType::Int,
                            default: "1".to_string(),
                            description: "Focus on float switch (0-2)".to_string(),
                            min: Some(0.0),
                            max: Some(2.0),
                            step: Some(1.0),
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "input:touchpad".to_string(),
                    title: "Touchpad".to_string(),
                    options: vec![
                        OptionDef {
                            name: "disable_while_typing".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Disable while typing".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "natural_scroll".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Natural scrolling".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "scroll_factor".to_string(),
                            option_type: OptionType::Float,
                            default: "1.0".to_string(),
                            description: "Scroll multiplier".to_string(),
                            min: Some(0.1),
                            max: Some(5.0),
                            step: Some(0.1),
                            choices: None,
                        },
                        OptionDef {
                            name: "tap-to-click".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Tap to click".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "tap-and-drag".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Tap and drag".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "clickfinger_behavior".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Clickfinger behavior".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "middle_button_emulation".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Middle button emulation".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "gestures".to_string(),
                    title: "Gestures".to_string(),
                    options: vec![
                        OptionDef {
                            name: "workspace_swipe".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Enable workspace swipe".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_fingers".to_string(),
                            option_type: OptionType::Int,
                            default: "3".to_string(),
                            description: "Swipe fingers".to_string(),
                            min: Some(3.0),
                            max: Some(4.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_distance".to_string(),
                            option_type: OptionType::Int,
                            default: "300".to_string(),
                            description: "Swipe distance (px)".to_string(),
                            min: Some(100.0),
                            max: Some(1000.0),
                            step: Some(50.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_touch".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Enable touchscreen edge swipe".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_invert".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Invert direction (touchpad)".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_touch_invert".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Invert direction (touchscreen)".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_min_speed_to_force".to_string(),
                            option_type: OptionType::Int,
                            default: "30".to_string(),
                            description: "Min speed to force switch".to_string(),
                            min: Some(0.0),
                            max: Some(100.0),
                            step: Some(5.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_cancel_ratio".to_string(),
                            option_type: OptionType::Float,
                            default: "0.5".to_string(),
                            description: "Cancel ratio threshold".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(0.1),
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_create_new".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Create new workspace on end swipe".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_direction_lock".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Lock swipe direction".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_direction_lock_threshold".to_string(),
                            option_type: OptionType::Int,
                            default: "10".to_string(),
                            description: "Direction lock threshold (px)".to_string(),
                            min: Some(0.0),
                            max: Some(100.0),
                            step: Some(5.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_forever".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Continue past neighbors".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_swipe_use_r".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Use r prefix for workspaces".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
            ],
        },
        Tab {
            id: "animations".to_string(),
            title: "Animations".to_string(),
            icon: '✨',
            sections: vec![Section {
                name: "animations".to_string(),
                title: "Animation Settings".to_string(),
                options: vec![OptionDef {
                    name: "enabled".to_string(),
                    option_type: OptionType::Bool,
                    default: "true".to_string(),
                    description: "Enable animations".to_string(),
                    min: None,
                    max: None,
                    step: None,
                    choices: None,
                }],
            }],
        },
        Tab {
            id: "misc".to_string(),
            title: "Misc".to_string(),
            icon: '🔧',
            sections: vec![Section {
                name: "misc".to_string(),
                title: "Miscellaneous".to_string(),
                options: vec![
                    OptionDef {
                        name: "disable_hyprland_logo".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Disable Hyprland logo".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "disable_splash_rendering".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Disable splash text".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "force_default_wallpaper".to_string(),
                        option_type: OptionType::Int,
                        default: "-1".to_string(),
                        description: "Force wallpaper (-1=random)".to_string(),
                        min: Some(-1.0),
                        max: Some(2.0),
                        step: Some(1.0),
                        choices: None,
                    },
                    OptionDef {
                        name: "font_family".to_string(),
                        option_type: OptionType::String,
                        default: "Sans".to_string(),
                        description: "Default font".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "background_color".to_string(),
                        option_type: OptionType::Color,
                        default: "0x111111".to_string(),
                        description: "Background color".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "vfr".to_string(),
                        option_type: OptionType::Bool,
                        default: "true".to_string(),
                        description: "Variable frame rate".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "vrr".to_string(),
                        option_type: OptionType::Int,
                        default: "0".to_string(),
                        description:
                            "Adaptive sync (0=off, 1=on, 2=fullscreen, 3=enabled+fullscreen hint)"
                                .to_string(),
                        min: Some(0.0),
                        max: Some(3.0),
                        step: Some(1.0),
                        choices: None,
                    },
                    OptionDef {
                        name: "mouse_move_enables_dpms".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Wake on mouse move".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "key_press_enables_dpms".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Wake on key press".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "disable_autoreload".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Disable config auto-reload".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "focus_on_activate".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Focus on activate request".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "layers_hog_keyboard_focus".to_string(),
                        option_type: OptionType::Bool,
                        default: "true".to_string(),
                        description: "Layers keep keyboard focus".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "animate_manual_resizes".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Animate manual resizes".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "animate_mouse_windowdragging".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Animate mouse dragging".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "enable_swallow".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Enable window swallowing".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "swallow_regex".to_string(),
                        option_type: OptionType::String,
                        default: "".to_string(),
                        description: "Swallow regex".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "swallow_exception_regex".to_string(),
                        option_type: OptionType::String,
                        default: "".to_string(),
                        description: "Swallow exception regex".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                ],
            }],
        },
        Tab {
            id: "cursor".to_string(),
            title: "Cursor".to_string(),
            icon: '🖱',
            sections: vec![Section {
                name: "cursor".to_string(),
                title: "Cursor Settings".to_string(),
                options: vec![
                    OptionDef {
                        name: "no_hardware_cursors".to_string(),
                        option_type: OptionType::Int,
                        default: "2".to_string(),
                        description: "Hardware cursors (0=on, 1=off, 2=auto)".to_string(),
                        min: Some(0.0),
                        max: Some(2.0),
                        step: Some(1.0),
                        choices: None,
                    },
                    OptionDef {
                        name: "inactive_timeout".to_string(),
                        option_type: OptionType::Int,
                        default: "0".to_string(),
                        description: "Hide after seconds (0=never)".to_string(),
                        min: Some(0.0),
                        max: Some(60.0),
                        step: Some(1.0),
                        choices: None,
                    },
                    OptionDef {
                        name: "no_warps".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Disable cursor warping".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "persistent_warps".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Persistent warps".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "enable_hyprcursor".to_string(),
                        option_type: OptionType::Bool,
                        default: "true".to_string(),
                        description: "Enable hyprcursor".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "hide_on_key_press".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Hide on key press".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "hide_on_touch".to_string(),
                        option_type: OptionType::Bool,
                        default: "true".to_string(),
                        description: "Hide on touch".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                    OptionDef {
                        name: "zoom_factor".to_string(),
                        option_type: OptionType::Float,
                        default: "1.0".to_string(),
                        description: "Cursor zoom factor".to_string(),
                        min: Some(1.0),
                        max: Some(10.0),
                        step: Some(0.5),
                        choices: None,
                    },
                    OptionDef {
                        name: "no_break_fs_vrr".to_string(),
                        option_type: OptionType::Bool,
                        default: "false".to_string(),
                        description: "Don't break fullscreen VRR".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    },
                ],
            }],
        },
        Tab {
            id: "advanced".to_string(),
            title: "Advanced".to_string(),
            icon: '⚡',
            sections: vec![
                Section {
                    name: "xwayland".to_string(),
                    title: "XWayland".to_string(),
                    options: vec![
                        OptionDef {
                            name: "enabled".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Enable XWayland".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "use_nearest_neighbor".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Pixelated scaling".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "force_zero_scaling".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Force 1x scale for HiDPI".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "opengl".to_string(),
                    title: "OpenGL".to_string(),
                    options: vec![OptionDef {
                        name: "nvidia_anti_flicker".to_string(),
                        option_type: OptionType::Bool,
                        default: "true".to_string(),
                        description: "NVIDIA anti-flicker".to_string(),
                        min: None,
                        max: None,
                        step: None,
                        choices: None,
                    }],
                },
                Section {
                    name: "render".to_string(),
                    title: "Rendering".to_string(),
                    options: vec![
                        OptionDef {
                            name: "direct_scanout".to_string(),
                            option_type: OptionType::Int,
                            default: "0".to_string(),
                            description: "Direct scanout (0=off, 1=on, 2=auto)".to_string(),
                            min: Some(0.0),
                            max: Some(2.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "expand_undersized_textures".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Expand undersized textures".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "binds".to_string(),
                    title: "Keybind Settings".to_string(),
                    options: vec![
                        OptionDef {
                            name: "pass_mouse_when_bound".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Pass mouse when bound".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "workspace_back_and_forth".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Workspace toggle".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "allow_workspace_cycles".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Allow workspace cycles".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "movefocus_cycles_fullscreen".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Focus cycles fullscreen".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "scroll_event_delay".to_string(),
                            option_type: OptionType::Int,
                            default: "300".to_string(),
                            description: "Scroll event delay (ms)".to_string(),
                            min: Some(0.0),
                            max: Some(1000.0),
                            step: Some(50.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "drag_threshold".to_string(),
                            option_type: OptionType::Int,
                            default: "10".to_string(),
                            description: "Drag threshold (px)".to_string(),
                            min: Some(0.0),
                            max: Some(50.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "focus_preferred_method".to_string(),
                            option_type: OptionType::Int,
                            default: "0".to_string(),
                            description: "Focus method (0=history, 1=length)".to_string(),
                            min: Some(0.0),
                            max: Some(1.0),
                            step: Some(1.0),
                            choices: None,
                        },
                    ],
                },
                Section {
                    name: "debug".to_string(),
                    title: "Debug".to_string(),
                    options: vec![
                        OptionDef {
                            name: "disable_logs".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Disable debug logs".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "disable_time".to_string(),
                            option_type: OptionType::Bool,
                            default: "true".to_string(),
                            description: "Disable log timestamps".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                        OptionDef {
                            name: "damage_tracking".to_string(),
                            option_type: OptionType::Int,
                            default: "2".to_string(),
                            description: "Damage tracking (0=none, 1=monitor, 2=full)".to_string(),
                            min: Some(0.0),
                            max: Some(2.0),
                            step: Some(1.0),
                            choices: None,
                        },
                        OptionDef {
                            name: "enable_stdout_logs".to_string(),
                            option_type: OptionType::Bool,
                            default: "false".to_string(),
                            description: "Enable stdout logs".to_string(),
                            min: None,
                            max: None,
                            step: None,
                            choices: None,
                        },
                    ],
                },
            ],
        },
    ]
}

pub fn get_flat_options() -> HashMap<String, OptionDef> {
    let mut map = HashMap::new();
    for tab in get_schema() {
        for section in tab.sections {
            for option in section.options {
                let key = format!("{}:{}", section.name, option.name);
                map.insert(key, option);
            }
        }
    }
    map
}
