#[derive(Debug, Clone, PartialEq)]
pub enum OptionType {
    Bool,
    Int,
    Float,
    String,
    Enum,
    Json,
    Color,
}

#[derive(Debug, Clone)]
pub struct WaybarOption {
    pub name: String,
    pub option_type: OptionType,
    pub default: String,
    pub description: String,
    pub choices: Option<Vec<String>>,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub step: Option<f64>,
}

#[derive(Debug, Clone)]
pub struct ModuleSchema {
    pub module_type: String,
    pub title: String,
    pub icon: char,
    pub options: Vec<WaybarOption>,
}

pub fn get_schema() -> Vec<ModuleSchema> {
    vec![
        ModuleSchema {
            module_type: "hyprland/workspaces".to_string(),
            title: "Workspaces".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{icon}".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-source".into(),
                    option_type: OptionType::String,
                    default: "{volume}%".into(),
                    description: "Source Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-source-muted".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Source Muted Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-icons".into(),
                    option_type: OptionType::Json,
                    default: "{}".into(),
                    description: "Icons mapping".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "all-outputs".into(),
                    option_type: OptionType::Bool,
                    default: "false".into(),
                    description: "Show on all outputs".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "active-only".into(),
                    option_type: OptionType::Bool,
                    default: "false".into(),
                    description: "Show active only".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "sort-by-number".into(),
                    option_type: OptionType::Bool,
                    default: "true".into(),
                    description: "Sort by number".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "sort-by-name".into(),
                    option_type: OptionType::Bool,
                    default: "false".into(),
                    description: "Sort by name".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "on-scroll-up".into(),
                    option_type: OptionType::String,
                    default: "hyprctl dispatch workspace e+1".into(),
                    description: "Scroll up action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "on-scroll-down".into(),
                    option_type: OptionType::String,
                    default: "hyprctl dispatch workspace e-1".into(),
                    description: "Scroll down action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "on-click".into(),
                    option_type: OptionType::String,
                    default: "activate".into(),
                    description: "Click action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "swap-icon-label".into(),
                    option_type: OptionType::Bool,
                    default: "false".into(),
                    description: "Swap icon and label".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "tooltip-format-wifi".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "WiFi Tooltip format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "tooltip-format-ethernet".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Ethernet Tooltip format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "hyprland/window".to_string(),
            title: "Window".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{}".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "icon".into(),
                    option_type: OptionType::Bool,
                    default: "false".into(),
                    description: "Show icon".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "icon-size".into(),
                    option_type: OptionType::Int,
                    default: "20".into(),
                    description: "Icon size".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "rewrite".into(),
                    option_type: OptionType::Json,
                    default: "{}".into(),
                    description: "Rewrite rules".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "separate-outputs".into(),
                    option_type: OptionType::Bool,
                    default: "false".into(),
                    description: "Separate outputs".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "clock".to_string(),
            title: "Clock".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "on-click".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Click Action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{:%H:%M}".into(),
                    description: "Time format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-alt".into(),
                    option_type: OptionType::String,
                    default: "{:%Y-%m-%d}".into(),
                    description: "Alt format (click)".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "tooltip-format".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Tooltip format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "timezone".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Timezone".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "locale".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Locale".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "interval".into(),
                    option_type: OptionType::Int,
                    default: "60".into(),
                    description: "Update interval".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "battery".to_string(),
            title: "Battery".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "interval".into(),
                    option_type: OptionType::Int,
                    default: "60".into(),
                    description: "Update interval".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "states".into(),
                    option_type: OptionType::Json,
                    default: "{\"warning\": 30, \"critical\": 15}".into(),
                    description: "Battery states".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{capacity}% {icon}".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-charging".into(),
                    option_type: OptionType::String,
                    default: "{capacity}% ".into(),
                    description: "Charging format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-plugged".into(),
                    option_type: OptionType::String,
                    default: "{capacity}% ".into(),
                    description: "Plugged format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-alt".into(),
                    option_type: OptionType::String,
                    default: "{time} {icon}".into(),
                    description: "Alt format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-icons".into(),
                    option_type: OptionType::Json,
                    default: "[\"\", \"\", \"\", \"\", \"\"]".into(),
                    description: "Icons".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "full-at".into(),
                    option_type: OptionType::Int,
                    default: "100".into(),
                    description: "Full at %".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "network".to_string(),
            title: "Network".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "on-click".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Click Action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-alt".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Alt Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "interface".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Interface (e.g. wlan0)".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{ifname}".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-wifi".into(),
                    option_type: OptionType::String,
                    default: "{essid} ({signalStrength}%) ".into(),
                    description: "WiFi Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-ethernet".into(),
                    option_type: OptionType::String,
                    default: "{ipaddr}/{cidr} ".into(),
                    description: "Ethernet Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-disconnected".into(),
                    option_type: OptionType::String,
                    default: "Disconnected ⚠".into(),
                    description: "Disconnected Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-linked".into(),
                    option_type: OptionType::String,
                    default: "{ifname} (No IP) ".into(),
                    description: "Linked Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "interval".into(),
                    option_type: OptionType::Int,
                    default: "10".into(),
                    description: "Update interval".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "family".into(),
                    option_type: OptionType::Enum,
                    default: "ipv4".into(),
                    description: "IP Family".into(),
                    choices: Some(vec!["ipv4".into(), "ipv6".into()]),
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "tooltip-format".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Tooltip format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "pulseaudio".to_string(),
            title: "PulseAudio".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "on-click-right".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Right Click Action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{volume}% {icon}".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-bluetooth".into(),
                    option_type: OptionType::String,
                    default: "{volume}% {icon}".into(),
                    description: "Bluetooth Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-muted".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Muted Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-icons".into(),
                    option_type: OptionType::Json,
                    default: "{\"default\": [\"\", \"\", \"\"]}".into(),
                    description: "Icons".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "scroll-step".into(),
                    option_type: OptionType::Float,
                    default: "5.0".into(),
                    description: "Scroll step".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "on-click".into(),
                    option_type: OptionType::String,
                    default: "pavucontrol".into(),
                    description: "Click action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "ignored-sinks".into(),
                    option_type: OptionType::Json,
                    default: "[\"Easy Effects Sink\"]".into(),
                    description: "Ignored sinks".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "cpu".to_string(),
            title: "CPU".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "on-click".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Click Action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "interval".into(),
                    option_type: OptionType::Int,
                    default: "10".into(),
                    description: "Interval".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{usage}% ".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "tooltip".into(),
                    option_type: OptionType::Bool,
                    default: "true".into(),
                    description: "Tooltip".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "memory".to_string(),
            title: "Memory".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "interval".into(),
                    option_type: OptionType::Int,
                    default: "30".into(),
                    description: "Interval".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{}% ".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "max-length".into(),
                    option_type: OptionType::Int,
                    default: "10".into(),
                    description: "Max Length".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "backlight".to_string(),
            title: "Backlight".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "on-click".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Click Action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "device".into(),
                    option_type: OptionType::String,
                    default: "intel_backlight".into(),
                    description: "Device".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{percent}% {icon}".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-icons".into(),
                    option_type: OptionType::Json,
                    default: "[\"\", \"\"]".into(),
                    description: "Icons".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "on-scroll-up".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Scroll up".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "on-scroll-down".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Scroll down".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "tray".to_string(),
            title: "Tray".to_string(),
            icon: '📥',
            options: vec![
                WaybarOption {
                    name: "icon-size".into(),
                    option_type: OptionType::Int,
                    default: "21".into(),
                    description: "Icon size".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "spacing".into(),
                    option_type: OptionType::Int,
                    default: "10".into(),
                    description: "Spacing".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "show-passive-items".into(),
                    option_type: OptionType::Bool,
                    default: "false".into(),
                    description: "Show passive items".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "idle_inhibitor".to_string(),
            title: "Idle Inhibitor".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "on-click".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Click Action".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{icon}".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-icons".into(),
                    option_type: OptionType::Json,
                    default: "{\"activated\": \"\", \"deactivated\": \"\"}".into(),
                    description: "Icons".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "start-activated".into(),
                    option_type: OptionType::Bool,
                    default: "false".into(),
                    description: "Start activated".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "temperature".to_string(),
            title: "Temperature".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "thermal-zone".into(),
                    option_type: OptionType::Int,
                    default: "0".into(),
                    description: "Thermal zone".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "hwmon-path".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Hwmon path".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "critical-threshold".into(),
                    option_type: OptionType::Int,
                    default: "80".into(),
                    description: "Critical threshold".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-critical".into(),
                    option_type: OptionType::String,
                    default: "{temperatureC}°C ".into(),
                    description: "Critical format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{temperatureC}°C ".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "interval".into(),
                    option_type: OptionType::Int,
                    default: "10".into(),
                    description: "Interval".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "custom".to_string(),
            title: "Custom Script".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "tooltip".into(),
                    option_type: OptionType::Bool,
                    default: "true".into(),
                    description: "Tooltip".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "exec".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Command to execute".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "exec-if".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Execute only if...".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "return-type".into(),
                    option_type: OptionType::Enum,
                    default: "".into(),
                    description: "Return type".into(),
                    choices: Some(vec!["".into(), "json".into()]),
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "interval".into(),
                    option_type: OptionType::Int,
                    default: "0".into(),
                    description: "Interval (seconds)".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format".into(),
                    option_type: OptionType::String,
                    default: "{}".into(),
                    description: "Format".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "format-icons".into(),
                    option_type: OptionType::Json,
                    default: "{}".into(),
                    description: "Icons".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "on-click".into(),
                    option_type: OptionType::String,
                    default: "".into(),
                    description: "Click command".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "signal".into(),
                    option_type: OptionType::Int,
                    default: "0".into(),
                    description: "Signal number".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "restart-interval".into(),
                    option_type: OptionType::Int,
                    default: "0".into(),
                    description: "Restart interval".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "group".to_string(),
            title: "Group".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "orientation".into(),
                    option_type: OptionType::Enum,
                    default: "horizontal".into(),
                    description: "Orientation".into(),
                    choices: Some(vec![
                        "horizontal".into(),
                        "vertical".into(),
                        "inherit".into(),
                    ]),
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "modules".into(),
                    option_type: OptionType::Json,
                    default: "[]".into(),
                    description: "Modules in group".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "drawer".into(),
                    option_type: OptionType::Json,
                    default: "{}".into(),
                    description: "Drawer configuration".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
        ModuleSchema {
            module_type: "general".to_string(),
            title: "General Settings".to_string(),
            icon: '',
            options: vec![
                WaybarOption {
                    name: "layer".into(),
                    option_type: OptionType::Enum,
                    default: "top".into(),
                    description: "Layer".into(),
                    choices: Some(vec!["top".into(), "bottom".into()]),
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "position".into(),
                    option_type: OptionType::Enum,
                    default: "top".into(),
                    description: "Position".into(),
                    choices: Some(vec![
                        "top".into(),
                        "bottom".into(),
                        "left".into(),
                        "right".into(),
                    ]),
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "height".into(),
                    option_type: OptionType::Int,
                    default: "30".into(),
                    description: "Height".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "width".into(),
                    option_type: OptionType::Int,
                    default: "0".into(),
                    description: "Width (0 = auto)".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "spacing".into(),
                    option_type: OptionType::Int,
                    default: "4".into(),
                    description: "Module Spacing".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "margin-top".into(),
                    option_type: OptionType::Int,
                    default: "0".into(),
                    description: "Margin Top".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "margin-bottom".into(),
                    option_type: OptionType::Int,
                    default: "0".into(),
                    description: "Margin Bottom".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "margin-left".into(),
                    option_type: OptionType::Int,
                    default: "0".into(),
                    description: "Margin Left".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "margin-right".into(),
                    option_type: OptionType::Int,
                    default: "0".into(),
                    description: "Margin Right".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "reload_style_on_change".into(),
                    option_type: OptionType::Bool,
                    default: "true".into(),
                    description: "Reload style on change".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
                WaybarOption {
                    name: "include".into(),
                    option_type: OptionType::Json,
                    default: "[]".into(),
                    description: "Include files".into(),
                    choices: None,
                    min: None,
                    max: None,
                    step: None,
                },
            ],
        },
    ]
}

pub fn get_module_schema(name: &str, schemas: &[ModuleSchema]) -> Option<ModuleSchema> {
    
    if let Some(s) = schemas.iter().find(|s| s.module_type == name) {
        return Some(s.clone());
    }

    
    if name.starts_with("custom/") {
        return schemas.iter().find(|s| s.module_type == "custom").cloned();
    }

    
    if name.starts_with("hyprland/") {
         return None;
    }

    None
}
